[package]
name = "iomath"
version = "0.1.0"
authors = ["x4kkk3r <x4kkk3r@github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
